import { Router, Request, Response } from 'express';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import axios from 'axios';

const router: Router = Router();

// Get __dirname equivalent in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface RouterConfig {
  routerIp: string;
  username: string;
  password: string;
  pollingInterval: number;
}

const CONFIG_FILE = path.join(__dirname, '../../config/router.json');
const AGENT_ENV_FILE = path.join(__dirname, '../../../agent/.env');
const AGENT_API_URL = process.env.AGENT_API_URL || 'http://localhost:5000';

// Test router connection via Python agent
router.post('/test', async (req: Request, res: Response) => {
  try {
    const { routerIp, username, password }: RouterConfig = req.body;

    if (!routerIp || !username || !password) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    // Basic validation
    const ipRegex = /^(\d{1,3}\.){3}\d{1,3}$/;
    if (!ipRegex.test(routerIp)) {
      return res.status(400).json({ error: 'Invalid IP address format' });
    }

    console.log(`Testing connection to ${routerIp} via Python agent...`);

    try {
      // Call Python agent API to test connection
      const response = await axios.post(`${AGENT_API_URL}/test-connection`, {
        routerIp,
        username,
        password
      }, {
        timeout: 15000 // 15 second timeout for router authentication
      });

      return res.json({
        success: response.data.success,
        message: response.data.message,
        details: {
          ip: routerIp,
          username: username,
          timestamp: new Date().toISOString()
        }
      });

    } catch (error) {
      if (axios.isAxiosError(error) && error.response) {
        // Agent returned an error response
        return res.json({
          success: false,
          message: error.response.data.message || 'Connection test failed'
        });
      } else {
        // Agent is not reachable
        return res.json({
          success: false,
          message: 'Cannot reach Python agent. Make sure the agent service is running.'
        });
      }
    }

  } catch (error) {
    console.error('Test connection error:', error);
    return res.status(500).json({ 
      success: false,
      error: 'Failed to test connection',
      message: error instanceof Error ? error.message : 'Unknown error'
    });
  }
});

// Save router configuration
router.post('/save', async (req: Request, res: Response) => {
  try {
    const config: RouterConfig = req.body;

    if (!config.routerIp || !config.username || !config.password) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    // Create config directory if it doesn't exist
    const configDir = path.dirname(CONFIG_FILE);
    try {
      await fs.mkdir(configDir, { recursive: true });
    } catch (err) {
      console.log('Config directory already exists');
    }

    // Save to backend config file (JSON)
    await fs.writeFile(CONFIG_FILE, JSON.stringify(config, null, 2), 'utf-8');
    console.log('✓ Saved configuration to:', CONFIG_FILE);

    // Create/update agent .env file
    const envContent = `# Router Configuration
ROUTER_IP=${config.routerIp}
ROUTER_USERNAME=${config.username}
ROUTER_PASSWORD=${config.password}
POLLING_INTERVAL=${config.pollingInterval}
BACKEND_URL=http://localhost:4000

# Generated by EdgeNet Setup
# Last Updated: ${new Date().toISOString()}
`;

    await fs.writeFile(AGENT_ENV_FILE, envContent, 'utf-8');
    console.log('✓ Saved configuration to:', AGENT_ENV_FILE);

    return res.json({
      success: true,
      message: 'Configuration saved successfully',
      paths: {
        backend: CONFIG_FILE,
        agent: AGENT_ENV_FILE
      }
    });

  } catch (error) {
    console.error('Save configuration error:', error);
    return res.status(500).json({ error: 'Failed to save configuration' });
  }
});

// Get current configuration
router.get('/current', async (_req: Request, res: Response) => {
  try {
    const configData = await fs.readFile(CONFIG_FILE, 'utf-8');
    const config: RouterConfig = JSON.parse(configData);
    
    // Don't send password to frontend
    const sanitized = {
      ...config,
      password: config.password ? '••••••••' : ''
    };

    res.json(sanitized);
  } catch (error) {
    // No config file exists yet
    res.status(404).json({ error: 'No configuration found' });
  }
});

export default router;
